// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PTYKill(arg1, arg2) {
  return window['go']['main']['App']['PTYKill'](arg1, arg2);
}

export function PTYResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['PTYResize'](arg1, arg2, arg3);
}

export function PTYSpawn(arg1) {
  return window['go']['main']['App']['PTYSpawn'](arg1);
}

export function PTYWrite(arg1, arg2) {
  return window['go']['main']['App']['PTYWrite'](arg1, arg2);
}

export function SSHConnect(arg1) {
  return window['go']['main']['App']['SSHConnect'](arg1);
}

export function SSHStartShell(arg1) {
  return window['go']['main']['App']['SSHStartShell'](arg1);
}

export function SSHWrite(arg1) {
  return window['go']['main']['App']['SSHWrite'](arg1);
}
