// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {colorscheme} from '../models';
import {profile} from '../models';
import {settings} from '../models';
import {session} from '../models';
import {api} from '../models';
import {telnet} from '../models';

export function ClearSessionState():Promise<void>;

export function GetAvailableShells():Promise<Array<string>>;

export function GetColorScheme(arg1:string):Promise<colorscheme.ColorScheme>;

export function GetColorSchemeNames():Promise<Array<string>>;

export function GetColorSchemes():Promise<Array<colorscheme.ColorScheme>>;

export function GetDefaultShell():Promise<string>;

export function GetDefaultShellPreferred():Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetHostname():Promise<string>;

export function GetPlatform():Promise<Record<string, string>>;

export function GetProfiles():Promise<Array<profile.ConnectionProfile>>;

export function GetSettings():Promise<settings.Settings>;

export function GetUsername():Promise<string>;

export function LoadSessionState():Promise<session.SessionState>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function PTYKill(arg1:string,arg2:string):Promise<void>;

export function PTYResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PTYSpawn(arg1:api.PTYSpawnParams):Promise<api.PTYSpawnResult>;

export function PTYWrite(arg1:string,arg2:string):Promise<void>;

export function ResetSettings():Promise<void>;

export function SFTPChmod(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SFTPDownload(arg1:api.SFTPDownloadParams):Promise<api.SFTPTransferResult>;

export function SFTPList(arg1:api.SFTPListParams):Promise<Array<api.SFTPFile>>;

export function SFTPOpen(arg1:api.SFTPOpenParams):Promise<api.SFTPOpenResult>;

export function SFTPReadlink(arg1:string,arg2:string):Promise<string>;

export function SFTPSymlink(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:api.SFTPUploadParams):Promise<api.SFTPTransferResult>;

export function SSHAddForward(arg1:api.PortForwardParams):Promise<api.PortForwardResult>;

export function SSHClose(arg1:api.SSHCloseParams):Promise<void>;

export function SSHConnect(arg1:api.SSHConnectParams):Promise<api.SSHConnectionResult>;

export function SSHListForwards(arg1:string):Promise<Array<api.PortForwardInfo>>;

export function SSHRemoveForward(arg1:api.PortForwardRemoveParams):Promise<void>;

export function SSHResize(arg1:api.SSHResizeParams):Promise<void>;

export function SSHStartShell(arg1:api.SSHSessionParams):Promise<api.SSHSessionResult>;

export function SSHWrite(arg1:api.SSHWriteParams):Promise<void>;

export function SaveProfiles(arg1:Array<profile.ConnectionProfile>):Promise<void>;

export function SaveSessionState(arg1:Array<session.TabState>):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SerialClose(arg1:string):Promise<void>;

export function SerialListPorts():Promise<Array<api.SerialPortInfo>>;

export function SerialOpen(arg1:api.SerialOpenParams):Promise<api.SerialOpenResult>;

export function SerialWrite(arg1:string,arg2:string):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function TelnetClose(arg1:string):Promise<void>;

export function TelnetConnect(arg1:string,arg2:number):Promise<telnet.TelnetConnectResult>;

export function TelnetResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TelnetWrite(arg1:string,arg2:string):Promise<void>;
