// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Greet(arg1:string):Promise<string>;

export function PTYKill(arg1:string,arg2:string):Promise<void>;

export function PTYResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PTYSpawn(arg1:api.PTYSpawnParams):Promise<api.PTYSpawnResult>;

export function PTYWrite(arg1:string,arg2:string):Promise<void>;

export function SSHConnect(arg1:api.SSHConnectParams):Promise<api.SSHConnectionResult>;

export function SSHStartShell(arg1:api.SSHSessionParams):Promise<api.SSHSessionResult>;

export function SSHWrite(arg1:api.SSHWriteParams):Promise<void>;
