// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSessionState() {
  return window['go']['main']['App']['ClearSessionState']();
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetDefaultShell() {
  return window['go']['main']['App']['GetDefaultShell']();
}

export function GetDefaultShellPreferred() {
  return window['go']['main']['App']['GetDefaultShellPreferred']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetHostname() {
  return window['go']['main']['App']['GetHostname']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function LoadSessionState() {
  return window['go']['main']['App']['LoadSessionState']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function PTYKill(arg1, arg2) {
  return window['go']['main']['App']['PTYKill'](arg1, arg2);
}

export function PTYResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['PTYResize'](arg1, arg2, arg3);
}

export function PTYSpawn(arg1) {
  return window['go']['main']['App']['PTYSpawn'](arg1);
}

export function PTYWrite(arg1, arg2) {
  return window['go']['main']['App']['PTYWrite'](arg1, arg2);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SSHConnect(arg1) {
  return window['go']['main']['App']['SSHConnect'](arg1);
}

export function SSHStartShell(arg1) {
  return window['go']['main']['App']['SSHStartShell'](arg1);
}

export function SSHWrite(arg1) {
  return window['go']['main']['App']['SSHWrite'](arg1);
}

export function SaveSessionState(arg1) {
  return window['go']['main']['App']['SaveSessionState'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}
