// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearNotifications() {
  return window['go']['main']['App']['ClearNotifications']();
}

export function ClearSessionState() {
  return window['go']['main']['App']['ClearSessionState']();
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function GetAuditLogPath() {
  return window['go']['main']['App']['GetAuditLogPath']();
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetColorScheme(arg1) {
  return window['go']['main']['App']['GetColorScheme'](arg1);
}

export function GetColorSchemeNames() {
  return window['go']['main']['App']['GetColorSchemeNames']();
}

export function GetColorSchemes() {
  return window['go']['main']['App']['GetColorSchemes']();
}

export function GetCredential(arg1) {
  return window['go']['main']['App']['GetCredential'](arg1);
}

export function GetDefaultShell() {
  return window['go']['main']['App']['GetDefaultShell']();
}

export function GetDefaultShellPreferred() {
  return window['go']['main']['App']['GetDefaultShellPreferred']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetHostname() {
  return window['go']['main']['App']['GetHostname']();
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUnreadNotifications() {
  return window['go']['main']['App']['GetUnreadNotifications']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function ImportSSHConfig() {
  return window['go']['main']['App']['ImportSSHConfig']();
}

export function IsOSKeyringAvailable() {
  return window['go']['main']['App']['IsOSKeyringAvailable']();
}

export function LoadSessionState() {
  return window['go']['main']['App']['LoadSessionState']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function PTYKill(arg1, arg2) {
  return window['go']['main']['App']['PTYKill'](arg1, arg2);
}

export function PTYResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['PTYResize'](arg1, arg2, arg3);
}

export function PTYSpawn(arg1) {
  return window['go']['main']['App']['PTYSpawn'](arg1);
}

export function PTYWrite(arg1, arg2) {
  return window['go']['main']['App']['PTYWrite'](arg1, arg2);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SFTPChmod(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPChmod'](arg1, arg2, arg3);
}

export function SFTPClose(arg1) {
  return window['go']['main']['App']['SFTPClose'](arg1);
}

export function SFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['SFTPDelete'](arg1, arg2);
}

export function SFTPDownload(arg1) {
  return window['go']['main']['App']['SFTPDownload'](arg1);
}

export function SFTPList(arg1) {
  return window['go']['main']['App']['SFTPList'](arg1);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPMkdirAll(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdirAll'](arg1, arg2);
}

export function SFTPOpen(arg1) {
  return window['go']['main']['App']['SFTPOpen'](arg1);
}

export function SFTPReadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPReadDir'](arg1, arg2);
}

export function SFTPReadlink(arg1, arg2) {
  return window['go']['main']['App']['SFTPReadlink'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPRmdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPRmdir'](arg1, arg2);
}

export function SFTPStat(arg1, arg2) {
  return window['go']['main']['App']['SFTPStat'](arg1, arg2);
}

export function SFTPSymlink(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPSymlink'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1) {
  return window['go']['main']['App']['SFTPUpload'](arg1);
}

export function SSHAddForward(arg1) {
  return window['go']['main']['App']['SSHAddForward'](arg1);
}

export function SSHClose(arg1) {
  return window['go']['main']['App']['SSHClose'](arg1);
}

export function SSHConnect(arg1) {
  return window['go']['main']['App']['SSHConnect'](arg1);
}

export function SSHListForwards(arg1) {
  return window['go']['main']['App']['SSHListForwards'](arg1);
}

export function SSHRemoveForward(arg1) {
  return window['go']['main']['App']['SSHRemoveForward'](arg1);
}

export function SSHResize(arg1) {
  return window['go']['main']['App']['SSHResize'](arg1);
}

export function SSHStartShell(arg1) {
  return window['go']['main']['App']['SSHStartShell'](arg1);
}

export function SSHWrite(arg1) {
  return window['go']['main']['App']['SSHWrite'](arg1);
}

export function SaveProfiles(arg1) {
  return window['go']['main']['App']['SaveProfiles'](arg1);
}

export function SaveSessionState(arg1) {
  return window['go']['main']['App']['SaveSessionState'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SerialClose(arg1) {
  return window['go']['main']['App']['SerialClose'](arg1);
}

export function SerialListPorts() {
  return window['go']['main']['App']['SerialListPorts']();
}

export function SerialOpen(arg1) {
  return window['go']['main']['App']['SerialOpen'](arg1);
}

export function SerialWrite(arg1, arg2) {
  return window['go']['main']['App']['SerialWrite'](arg1, arg2);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function StoreCredential(arg1, arg2) {
  return window['go']['main']['App']['StoreCredential'](arg1, arg2);
}

export function TelnetClose(arg1) {
  return window['go']['main']['App']['TelnetClose'](arg1);
}

export function TelnetConnect(arg1, arg2) {
  return window['go']['main']['App']['TelnetConnect'](arg1, arg2);
}

export function TelnetResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TelnetResize'](arg1, arg2, arg3);
}

export function TelnetWrite(arg1, arg2) {
  return window['go']['main']['App']['TelnetWrite'](arg1, arg2);
}
