// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {session} from '../models';
import {api} from '../models';

export function ClearSessionState():Promise<void>;

export function GetAvailableShells():Promise<Array<string>>;

export function GetDefaultShell():Promise<string>;

export function GetDefaultShellPreferred():Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetHostname():Promise<string>;

export function GetPlatform():Promise<Record<string, string>>;

export function GetSettings():Promise<settings.Settings>;

export function GetUsername():Promise<string>;

export function LoadSessionState():Promise<session.SessionState>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function PTYKill(arg1:string,arg2:string):Promise<void>;

export function PTYResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PTYSpawn(arg1:api.PTYSpawnParams):Promise<api.PTYSpawnResult>;

export function PTYWrite(arg1:string,arg2:string):Promise<void>;

export function ResetSettings():Promise<void>;

export function SSHConnect(arg1:api.SSHConnectParams):Promise<api.SSHConnectionResult>;

export function SSHStartShell(arg1:api.SSHSessionParams):Promise<api.SSHSessionResult>;

export function SSHWrite(arg1:api.SSHWriteParams):Promise<void>;

export function SaveSessionState(arg1:Array<session.TabState>):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SetWindowTitle(arg1:string):Promise<void>;
